import { NextRequest } from 'next/server'
import { z } from 'zod'
import { createClient } from '@/lib/supabase/server'
import { getAnthropic, AI_MODELS } from '@/lib/anthropic'
import { BLUEPRINT_SYSTEM_PROMPT, buildBlueprintPrompt, getScoreLabel } from '@/lib/prompts/blueprint'
import type { BlueprintContent } from '@/types/blueprint'

const Schema = z.object({
  idea_text: z.string().min(10).max(500),
  email: z.string().email(),
})

const DAILY_LIMIT = 3

export const runtime = 'nodejs'
export const maxDuration = 300

function generateBuildKitFiles(content: BlueprintContent) {
  const { baslik, tech_stack, db_semasi, api_tasarim, ui_mimarisi, gelir_modeli } = content

  const cursorrules = `# ${baslik} — .cursorrules
# Generated by SystemMD Blueprint Platform

## PROJECT
${baslik} — ${content.deger_onerisi.tek_cumle}

## TECH STACK
- Frontend: ${tech_stack.frontend}
- Backend: ${tech_stack.backend}
- Database: ${tech_stack.veritabani}
- Auth: ${tech_stack.auth}
- AI: ${tech_stack.ai}
- Email: ${tech_stack.email}
- Payments: ${tech_stack.odeme}
- Hosting: ${tech_stack.hosting}

## RULES
1. TypeScript strict mode — no any
2. Server-side API keys only
3. Supabase RLS always enabled
4. Handle all UI states: loading + error + empty + content`

  const apiList = api_tasarim.endpointler
    .map(e => `### ${e.method} ${e.yol}\n${e.aciklama}`)
    .join('\n\n')

  const pageList = ui_mimarisi.sayfalar
    .map(p => `- ${p.yol} — ${p.ad}: ${p.aciklama}`)
    .join('\n')

  const planList = gelir_modeli.planlar
    .map(p => `- ${p.ad}: $${p.fiyat_aylik}/mo — ${p.hedef}`)
    .join('\n')

  const build_md = `# ${baslik} — Build Guide
Generated by SystemMD Blueprint Platform.

## VALUE PROPOSITION
${content.deger_onerisi.tek_cumle}

## PROBLEM
${content.problem.tanim}

## MVP FEATURES
${content.mvp_kapsam.ozellikler.map(f => `- ${f}`).join('\n')}

## API DESIGN
${apiList}

## PAGES
${pageList}

## REVENUE MODEL
${gelir_modeli.model_turu}

${planList}

Target MRR (3mo): ${gelir_modeli.hedef_mrr_3ay}
Target MRR (12mo): ${gelir_modeli.hedef_mrr_12ay}

## SCORE
- Total: ${content.skor.toplam}/100
- Market: ${content.skor.pazar}/100
- Tech: ${content.skor.teknoloji}/100
- Revenue: ${content.skor.gelir}/100

## THIS WEEK
${content.geri_bildirim.ilk_hafta_aksiyonlari.map((a, i) => `${i + 1}. ${a}`).join('\n')}`

  const schema_sql = db_semasi.sql

  const envKeys = [
    '# Supabase',
    'NEXT_PUBLIC_SUPABASE_URL=',
    'NEXT_PUBLIC_SUPABASE_ANON_KEY=',
    'SUPABASE_SERVICE_ROLE_KEY=',
    '',
    '# Anthropic',
    'ANTHROPIC_API_KEY=',
    '',
    '# App',
    'NEXT_PUBLIC_APP_URL=http://localhost:3000',
  ]

  const env_example = envKeys.join('\n')

  const slug = baslik.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')

  const readme_md = `# ${baslik}

${content.deger_onerisi.tek_cumle}

## Quick Start

\`\`\`bash
npx create-next-app@latest ${slug} --typescript --tailwind --eslint --app --src-dir
cd ${slug}
npm install
\`\`\`

## Tech Stack
- Frontend: ${tech_stack.frontend}
- Database: ${tech_stack.veritabani}
- Auth: ${tech_stack.auth}
- Hosting: ${tech_stack.hosting}

---
*Generated by SystemMD · systemmd.com*`

  return { cursorrules, build_md, schema_sql, env_example, readme_md }
}

function sseMessage(data: Record<string, unknown>): string {
  return `data: ${JSON.stringify(data)}\n\n`
}

export async function POST(req: NextRequest) {
  const encoder = new TextEncoder()

  let rawBody: unknown
  try {
    rawBody = await req.json()
  } catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON' }), { status: 400 })
  }

  const parsed = Schema.safeParse(rawBody)
  if (!parsed.success) {
    return new Response(JSON.stringify({ error: parsed.error.issues.map(i => i.message).join(', ') }), { status: 400 })
  }

  const { idea_text, email } = parsed.data

  const stream = new ReadableStream({
    async start(controller) {
      const send = (data: Record<string, unknown>) => {
        controller.enqueue(encoder.encode(sseMessage(data)))
      }

      // Immediate first ping to confirm stream is alive
      send({ type: 'status', message: 'Connecting...' })

      try {
        const supabase = await createClient()

        // Check email is verified — must be first DB check
        const { data: waitlistRow } = await (supabase as any)
          .from('waitlist')
          .select('verified')
          .eq('email', email.toLowerCase().trim())
          .single()

        if (!waitlistRow || !waitlistRow.verified) {
          send({
            type: 'error',
            message: 'Please verify your email first. Check your inbox for the verification link.',
          })
          controller.close()
          return
        }

        const todayStart = new Date()
        todayStart.setHours(0, 0, 0, 0)

        const { count } = await (supabase as any)
          .from('public_blueprints')
          .select('id', { count: 'exact', head: true })
          .eq('email', email.toLowerCase().trim())
          .gte('created_at', todayStart.toISOString())

        if ((count ?? 0) >= DAILY_LIMIT) {
          send({ type: 'error', message: `Daily limit reached (${DAILY_LIMIT} blueprints/day). Come back tomorrow!` })
          controller.close()
          return
        }

        const { data: record, error: insertError } = await (supabase as any)
          .from('public_blueprints')
          .insert({ email: email.toLowerCase().trim(), idea_text, status: 'generating' })
          .select('id')
          .single()

        if (insertError || !record) {
          send({ type: 'error', message: 'Failed to create blueprint record.' })
          controller.close()
          return
        }

        const blueprintId = record.id
        send({ type: 'status', message: 'Starting generation...', blueprint_id: blueprintId })

        const userPrompt = buildBlueprintPrompt({ idea_text, industry: undefined, stage: 'idea', target_users: undefined })
        const modelId = AI_MODELS['standard']

        let fullText = ''
        let chunkCount = 0

        const timeoutId = setTimeout(() => {
          send({ type: 'error', message: 'Generation timed out. Please try again.' })
          controller.close()
        }, 90000)

        try {
          const claudeStream = getAnthropic().messages.stream({
            model: modelId,
            max_tokens: 8192,
            system: BLUEPRINT_SYSTEM_PROMPT,
            messages: [{ role: 'user', content: userPrompt }],
          })

          for await (const event of claudeStream) {
            if (event.type === 'content_block_delta' && event.delta.type === 'text_delta') {
              const chunk = event.delta.text
              fullText += chunk
              chunkCount++
              send({ type: 'chunk', content: chunk })

              if (chunkCount % 20 === 0) {
                const estimatedProgress = Math.min(Math.round((fullText.length / 6000) * 85), 85)
                send({ type: 'progress', value: estimatedProgress })
              }
            }
          }
        } finally {
          clearTimeout(timeoutId)
        }

        send({ type: 'progress', value: 90 })

        let content: BlueprintContent
        try {
          const jsonText = fullText.replace(/^```(?:json)?\n?/i, '').replace(/\n?```$/i, '').trim()
          content = JSON.parse(jsonText) as BlueprintContent
        } catch {
          await (supabase as any).from('public_blueprints').update({ status: 'failed' }).eq('id', blueprintId)
          send({ type: 'error', message: 'Failed to parse blueprint JSON.' })
          controller.close()
          return
        }

        content.skor.etiket = getScoreLabel(content.skor.toplam)

        const kitFiles = generateBuildKitFiles(content)

        await (supabase as any).from('public_blueprints').update({
          title: content.baslik || idea_text.substring(0, 100),
          status: 'complete',
          score_total: content.skor.toplam,
          content: content as unknown,
          cursorrules: kitFiles.cursorrules,
          build_md: kitFiles.build_md,
          schema_sql: kitFiles.schema_sql,
          env_example: kitFiles.env_example,
          readme_md: kitFiles.readme_md,
        }).eq('id', blueprintId)

        send({ type: 'progress', value: 100 })
        send({ type: 'complete', blueprint_id: blueprintId, title: content.baslik, score: content.skor.toplam })

      } catch (err) {
        const msg = err instanceof Error ? err.message : 'Unexpected error'
        send({ type: 'error', message: msg })
      } finally {
        controller.close()
      }
    },
  })

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      'Connection': 'keep-alive',
      'X-Accel-Buffering': 'no',
    },
  })
}
