import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import JSZip from 'jszip'

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params

  if (!id) {
    return NextResponse.json({ error: 'Blueprint ID required' }, { status: 400 })
  }

  try {
    const supabase = await createClient()

    const { data: blueprint, error } = await (supabase as any)
      .from('public_blueprints')
      .select('title, cursorrules, build_md, schema_sql, env_example, readme_md, idea_text, status')
      .eq('id', id)
      .eq('status', 'complete')
      .single()

    if (error || !blueprint) {
      return NextResponse.json({ error: 'Blueprint not found' }, { status: 404 })
    }

    const zip = new JSZip()

    const folderName = (blueprint.title || blueprint.idea_text || 'blueprint')
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-]/g, '')
      .substring(0, 40)

    const folder = zip.folder(folderName)!

    if (blueprint.readme_md)   folder.file('README.md',    blueprint.readme_md)
    if (blueprint.build_md)    folder.file('BUILD.md',     blueprint.build_md)
    if (blueprint.cursorrules) folder.file('.cursorrules', blueprint.cursorrules)
    if (blueprint.schema_sql)  folder.file('schema.sql',   blueprint.schema_sql)
    if (blueprint.env_example) folder.file('.env.example', blueprint.env_example)

    folder.file('quickstart.sh', `#!/bin/bash
# ${blueprint.title} — Quick Start
# Generated by SystemMD Blueprint Platform

echo "Setting up ${blueprint.title}..."

npx create-next-app@latest ${folderName} \\
  --typescript \\
  --tailwind \\
  --eslint \\
  --app \\
  --src-dir

cd ${folderName}

echo "Done. Next steps:"
echo "  1. Copy .env.example to .env.local and fill in your values"
echo "  2. Run schema.sql in your Supabase SQL editor"
echo "  3. Read BUILD.md for full architecture guide"
echo "  4. Use .cursorrules in your AI code editor"
`)

    const zipBuffer = await zip.generateAsync({
      type: 'nodebuffer',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    })

    return new Response(new Uint8Array(zipBuffer), {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${folderName}-blueprint.zip"`,
        'Content-Length': String(zipBuffer.byteLength),
        'Cache-Control': 'private, max-age=3600',
      },
    })
  } catch (err) {
    console.error('Download error:', err)
    return NextResponse.json({ error: 'Failed to generate ZIP' }, { status: 500 })
  }
}
